// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for Era.
const (
	Baroque              Era = "Baroque"
	Classical            Era = "Classical"
	EarlyRomantics       Era = "Early Romantics"
	LateRomantics        Era = "Late Romantics"
	N20thCentury         Era = "20th Century"
	N21stCentury         Era = "21st Century"
	NationalistRomantics Era = "Nationalist Romantics"
)

// Defines values for GetV1ComposersParamsSort.
const (
	BirthYear GetV1ComposersParamsSort = "birth_year"
	CreatedAt GetV1ComposersParamsSort = "created_at"
	DeathYear GetV1ComposersParamsSort = "death_year"
	Name      GetV1ComposersParamsSort = "name"
)

// Defines values for GetV1ComposersParamsOrder.
const (
	Asc  GetV1ComposersParamsOrder = "asc"
	Desc GetV1ComposersParamsOrder = "desc"
)

// Composer `(name, birth_year)` must be unique. Enforced at the database level; surfaced as 409 Conflict.
type Composer struct {
	// AlsoKnownAs Alternative names/aliases.
	AlsoKnownAs *[]string `json:"also_known_as,omitempty"`
	BirthYear   *int      `json:"birth_year"`

	// Country ISO 3166-1 alpha-2 code.
	Country   *string    `json:"country"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	DeathYear *int       `json:"death_year"`

	// Description Optional biographical text (Markdown allowed).
	Description *string `json:"description"`
	Era         Era     `json:"era"`

	// Id Server-generated UUID.
	Id    openapi_types.UUID `json:"id"`
	Links *struct {
		Self *string `json:"self,omitempty"`
	} `json:"links,omitempty"`

	// Name Primary display name (e.g., "Ludwig van Beethoven").
	Name string `json:"name"`

	// Slug URL-friendly slug generated from the name.
	Slug      *string    `json:"slug,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// ComposerCreate defines model for ComposerCreate.
type ComposerCreate struct {
	AlsoKnownAs *[]string `json:"also_known_as,omitempty"`
	BirthYear   *int      `json:"birth_year"`
	Country     *string   `json:"country"`
	DeathYear   *int      `json:"death_year"`
	Description *string   `json:"description"`
	Era         Era       `json:"era"`
	Name        string    `json:"name"`
}

// ComposerUpdate JSON Merge Patch document to update a composer.
type ComposerUpdate struct {
	AlsoKnownAs *[]string `json:"also_known_as"`
	BirthYear   *int      `json:"birth_year"`
	Country     *string   `json:"country"`
	DeathYear   *int      `json:"death_year"`
	Description *string   `json:"description"`
	Era         *Era      `json:"era,omitempty"`
	Name        *string   `json:"name"`
}

// ComposersListResponse defines model for ComposersListResponse.
type ComposersListResponse struct {
	Data  []Composer `json:"data"`
	Links struct {
		First *string `json:"first"`
		Last  *string `json:"last"`
		Next  *string `json:"next"`
		Prev  *string `json:"prev"`
		Self  *string `json:"self,omitempty"`
	} `json:"links"`
	Meta struct {
		Page       int `json:"page"`
		PerPage    int `json:"per_page"`
		Total      int `json:"total"`
		TotalPages int `json:"total_pages"`
	} `json:"meta"`
}

// Era defines model for Era.
type Era string

// Problem RFC 7807 Problem Details
type Problem struct {
	Detail   *string              `json:"detail,omitempty"`
	Errors   *map[string][]string `json:"errors,omitempty"`
	Instance *string              `json:"instance,omitempty"`
	Status   int                  `json:"status"`
	Title    string               `json:"title"`
	Type     *string              `json:"type,omitempty"`
}

// GetV1ComposersParams defines parameters for GetV1Composers.
type GetV1ComposersParams struct {
	// Q Case-insensitive search in name and aliases.
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// Era Filter by musical era.
	Era *Era `form:"era,omitempty" json:"era,omitempty"`

	// Country ISO 3166-1 alpha-2 country code (e.g., "DE", "RU").
	Country      *string                    `form:"country,omitempty" json:"country,omitempty"`
	BirthYearGte *int                       `form:"birth_year_gte,omitempty" json:"birth_year_gte,omitempty"`
	BirthYearLte *int                       `form:"birth_year_lte,omitempty" json:"birth_year_lte,omitempty"`
	Page         *int                       `form:"page,omitempty" json:"page,omitempty"`
	PerPage      *int                       `form:"per_page,omitempty" json:"per_page,omitempty"`
	Sort         *GetV1ComposersParamsSort  `form:"sort,omitempty" json:"sort,omitempty"`
	Order        *GetV1ComposersParamsOrder `form:"order,omitempty" json:"order,omitempty"`
}

// GetV1ComposersParamsSort defines parameters for GetV1Composers.
type GetV1ComposersParamsSort string

// GetV1ComposersParamsOrder defines parameters for GetV1Composers.
type GetV1ComposersParamsOrder string

// PostV1ComposersJSONRequestBody defines body for PostV1Composers for application/json ContentType.
type PostV1ComposersJSONRequestBody = ComposerCreate

// PatchV1ComposersIdApplicationMergePatchPlusJSONRequestBody defines body for PatchV1ComposersId for application/merge-patch+json ContentType.
type PatchV1ComposersIdApplicationMergePatchPlusJSONRequestBody = ComposerUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List composers (offset pagination)
	// (GET /v1/composers)
	GetV1Composers(ctx echo.Context, params GetV1ComposersParams) error
	// Create a composer
	// (POST /v1/composers)
	PostV1Composers(ctx echo.Context) error
	// Delete a composer
	// (DELETE /v1/composers/{id})
	DeleteV1ComposersId(ctx echo.Context, id openapi_types.UUID) error
	// Get a composer by ID
	// (GET /v1/composers/{id})
	GetV1ComposersId(ctx echo.Context, id openapi_types.UUID) error
	// Update a composer (merge-patch)
	// (PATCH /v1/composers/{id})
	PatchV1ComposersId(ctx echo.Context, id openapi_types.UUID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetV1Composers converts echo context to params.
func (w *ServerInterfaceWrapper) GetV1Composers(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetV1ComposersParams
	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, false, "q", ctx.QueryParams(), &params.Q)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter q: %s", err))
	}

	// ------------- Optional query parameter "era" -------------

	err = runtime.BindQueryParameter("form", true, false, "era", ctx.QueryParams(), &params.Era)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter era: %s", err))
	}

	// ------------- Optional query parameter "country" -------------

	err = runtime.BindQueryParameter("form", true, false, "country", ctx.QueryParams(), &params.Country)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter country: %s", err))
	}

	// ------------- Optional query parameter "birth_year_gte" -------------

	err = runtime.BindQueryParameter("form", true, false, "birth_year_gte", ctx.QueryParams(), &params.BirthYearGte)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter birth_year_gte: %s", err))
	}

	// ------------- Optional query parameter "birth_year_lte" -------------

	err = runtime.BindQueryParameter("form", true, false, "birth_year_lte", ctx.QueryParams(), &params.BirthYearLte)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter birth_year_lte: %s", err))
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, false, "per_page", ctx.QueryParams(), &params.PerPage)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter per_page: %s", err))
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", ctx.QueryParams(), &params.Sort)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sort: %s", err))
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameter("form", true, false, "order", ctx.QueryParams(), &params.Order)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter order: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetV1Composers(ctx, params)
	return err
}

// PostV1Composers converts echo context to params.
func (w *ServerInterfaceWrapper) PostV1Composers(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostV1Composers(ctx)
	return err
}

// DeleteV1ComposersId converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteV1ComposersId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteV1ComposersId(ctx, id)
	return err
}

// GetV1ComposersId converts echo context to params.
func (w *ServerInterfaceWrapper) GetV1ComposersId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetV1ComposersId(ctx, id)
	return err
}

// PatchV1ComposersId converts echo context to params.
func (w *ServerInterfaceWrapper) PatchV1ComposersId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PatchV1ComposersId(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/v1/composers", wrapper.GetV1Composers)
	router.POST(baseURL+"/v1/composers", wrapper.PostV1Composers)
	router.DELETE(baseURL+"/v1/composers/:id", wrapper.DeleteV1ComposersId)
	router.GET(baseURL+"/v1/composers/:id", wrapper.GetV1ComposersId)
	router.PATCH(baseURL+"/v1/composers/:id", wrapper.PatchV1ComposersId)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaXVPbuBr+KxqdvaCzSbANlJIzO2daoB16aMtA2YtSDqtYbxK1tuRKcmimk/9+RpK/",
	"7XyQ0u1e9IpYtl+9ej8ePY/MNxyKOBEcuFZ4+A2rcAoxsT+PzQ0F0vymoELJEs0Ex0P81w4nMfTQiEk9",
	"vZsDkU/+QnGqNBoBSjn7ksIAnfKxkCFQRDTSU0CUaDIiClAEM4j+jVQqx8TeV2jfO0LHgo8jFurBR457",
	"OJEiAakZWFdIpMTdZy7u+Z3zjcKYpJHGw5vbXsO555EGyYlmM0DGTbVLIkYUqAHuYaYhtgZixs+BT/QU",
	"D/0e1vME8BArLRmf4EUxQKQkc3NdrtS+TL6yOI3xMPA9r2dsuUvfM5c8jSIyigAPtUyhsMW4hglIYy0U",
	"Kddy3g7s2dU7tOc/fdr3EYmSKekHKBQUjOdNqwnRZp14iP9387z/4fZbsPgNd6wklEA00DuizXRjIWPz",
	"C1Oioa9ZDLiHJRD6jkfzhsOlDQrkEVdfW3IzAu/sDxKhERMTSZIpC0mENHzVaOcNkZ+puOeIRJG4B/qk",
	"Ky4t50ESM81vEsZ4iP+1W9b7blbsu6eSmCcZbftzBXIGsj8BDtLEEV1fn52YeYtIpimjXYGPGP9sS61e",
	"ygqicS0TqWTt1xdLsyJGnyDUZgJT3G2HLySLiZwjylQSkbltAbQDg8mghz7i85TeswmaEY5eAOipmAH/",
	"iG0g13SEitJJe7bry/P+WDLgNJoj8wgqIzWWIradb1wYbFJnaUK/s1Zt3L6kTALFwxtsM2Pj5Oqg1g61",
	"+W47ApwD4LF9p53K1aj0j4OabRHkh3b/I7Zv3g8r490okEptrKqAa1so7fJ/ffXuLXoDcgLoguhwiqgI",
	"0xi4RlogV12IoDCzMli/r21aNEvC9quIHquI1phcrCgWdc6UvgSVCK46UMPwoFqqV3lVcLAOoFiywYyZ",
	"VLpjh1kbpIhs9x6Hr1u9l0iYbfPexjtoK0MxuNDXA5aQSY4bWRV2lVwC8q54Mi/fRvV2vaeFJlHNvLf0",
	"MTuBWvdwA8KsUxX/8inrNtvo1jBjyzILUV5bXZB46loJuPHuBr8gUnxJzazHEVHKsDXcw6dERnN0KWLC",
	"NQsV7uG3xPE6pnRt/NxAZHUg8PQUHQPXqZybS1/p4vK2oxoupBhFELex+fLlMTp85h2i7Al0ApqwSLVA",
	"mNpx86sDN6SQDqkpZW4FF7WXiy5eu6+3Ism40oSHsL6We1hpotPqPNXSYTqCFS5sxDXLQnDmiik7Csf6",
	"PhZ2Sjd3mXz0JlUsRMdEk0hM0POLM9zDM5DKJcUb+APPuCYS4CRheIj3Bt5gD9udZGpXuDvzd/Mt0w5M",
	"QHekF3QquUIEJWTCuGWctrrEuNhw1QBdpUkipFZozIwuZHyCCKdICakZnzitafJpy/OM4iF+BfpPv8By",
	"65gkMWjrzE3TjWOioM+4Aq6YlZwKiAyniHHHvM1kVf1p3vmSgq1tt9fgLybYFu83YC/N+V/aZaHR3Ohv",
	"mwCQZNlMjgKXc63dD9vzdSpUyw6sUi2VxsnpR2z+Xl5n+qLLoZxYVJ3ajFEYz7oslsTnbqKhHtmVpKON",
	"smsniH7IBBmIl2YLVeGv3muWGix3hg6jgfF04/1s2Rymn7rtFxQ72zCyywpBrZHDmkK73TjtQlKQSxwg",
	"KqzM765MUXeZvzVY6JibhZ7A88yfUHAN3KIQSZKIhRYudj8pxz/hK4mTqGQTvhX6aWyEuO1RqTTKUjAj",
	"UQolD7xpiYAb/HqArgboBQmnxsUqlfefPjuo0HF8cloP2BAHXnDQ9476nv/eD4aeN/S8D/UID/3DA695",
	"aPYKZEx4AZwGRI1yz3Z3lIBkgg4ypTSs7PrMQCY5OCDB6Cjse+OntL8/OvT6z6gP/WB8cDQORnuh5/m4",
	"Qlgdg8NTrRM13N0lCRtkIRyEIq7h/+5Gtgvijl+LKeEcXcGIKM0Id2HMjy/wJ3u7r/Lb/ZG7XT156I6h",
	"KY1iARnH3mgF/zGJ/8P/mHpe8DTvxT8CD+eM+yFW9rrMOAL+ADNBlxVHxw377j0kQUuXV+Xbljf7VRJt",
	"YCejxsHBXoP/+nsLyzI226m6dZc10Dhb/K8lO2VjmhdKsoB2xHisQOeEggn+xGw8ZGK7sqQkt0YOCCeW",
	"6tzhQqgGeTDMCpR+Iej8gUDi2ro4pTNDBXY0IaMJE4eHXgsmahDwLDhcBwGGuSSMcKZ02fhVkp91XNeR",
	"It4ifdkp26LOR40GXLRA2d8qlvS7Y7gGav0PPyLOFmJHh4fhHg0c7vX34cDvH5FDr++HAT0ckz3wvGBb",
	"iN3I9mJ1wguEjezd/sxga+XuGoD1P2xTMl1NfpyluoenQGimIM6FK47OA+x8s+NwH81RluLaoV3p1Rol",
	"ZdzZX0kZEidGf++q0hGhd/l4SRMydYrfkMjMDhS9vnr3dlAqtOG+pZeZEntBKLp0oPOQkOYyuiOiNYtm",
	"fUdbro+m7jnoXmCeVXTP9NRmRBkFVciosjsRiSQQOkfwlSmtXNvkSt1V6Q2uf480giwU8SgDdjdHpd9v",
	"F9V4HpXxzD9LPlIwc3NoJ/MrFFxpSRjXaMZE5LwTTj3+XlmykPb7yhObgiDYMgUzEjFatEI7B38W99GY",
	"sAhoPbYFHGbhje2hd0Wn3WYAdoOZQjmK2+zl6RAc8oZTTpsDRdYRVU9CEJRJuOaJFCEoRUYRoFOumZ4/",
	"UkK6TKOdMk7Irf5Jgzo4mKkc7i9hCote/Txj9xujCxfyCFwn1CnEiR2vkIgz2j6DsBIoIXpabsP2U1d9",
	"3+wGrs7PlR3CZ78Nlm8FOs5qzgLB/gOq8LsT9VZo9FKknDYy4QK2PhO9/Bxp1XHPzwr2Q1WmlS2r2Mw/",
	"QURmbc9Co8N+KcqWonwcwmNUzUObsVpKXOi7se2r1bsyFxrZ5+rUY79E6WqHPgY0L+v4V6Ar7Y5Gc3R2",
	"slyomS2qQ6mZ4Z/T+JsIwhjkBPrW986kueq6y5r4jnB6Z0+ZV2PC+QDNBhXSfluFgefvt6nI7Mv4Rqrt",
	"oSCXtdCD17RKxj1//0vGPbqMC9773iOj2nWW++8WVEX/t6HtjFuahyrNVvwDx8/UVz+LVn2PtgtzmfT4",
	"0u7vlWXu+5Wtc8YnSAtEUCFcm6psCzX2QwRLY4O8bv7nEdqp1PiyQ037LxNuvEn8TzlNBONaobGQKCac",
	"TExwwspBZ/FFLx9qfztcYiX/cHkv5OeKJXe5sZUEpD0eqTpTGdvYjoRQSMr4pGKnMra4Xfw/AAD//9fh",
	"VLIzLQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
